### ISSUE TITLE
Unresolved external symbols when linking C++ code to chemfiles in Windows with MSVC 2019

### ISSUE THREAD

**Issue by ShoubhikRaj** [chemfiles/chemfiles#417] opened 2021-08-18 10:24 UTC
I am compiling the chemfiles library with MSVC 2019 (and the cmake provided therein). The build was done as shown in the installation instructions, without any extra flags except the `-DCMAKE_INSTALL_PREFIX`. Then I built the library with Visual Studio 2019, and the static library `chemfiles.lib` and the include files were installed without any compiler errors. (There were a lot of compiler warnings however).

When I attempt to link the test C++ code from [this](https://chemfiles.org/chemfiles/latest/cxx-tutorials.html) page, I get 5 unresolved external symbols error from the visual C++ linker.

```
G:\mypath> cl /MD test_prog1.cpp /IG:\chemfiles\include /link C:\chemfiles\lib\chemfiles.lib
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29913 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

test_prog1.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\ostream(375): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\ostream(368): note: while compiling class template member function 'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(unsigned __int64)'
test_prog1.cpp(21): note: see reference to function template instantiation 'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(unsigned __int64)' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\ostream(641): note: see reference to class template instantiation 'std::basic_ostream<char,std::char_traits<char>>' being compiled
Microsoft (R) Incremental Linker Version 14.28.29913.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:test_prog1.exe
G:\chemfiles\lib\chemfiles.lib
test_prog1.obj
   Creating library test_prog1.lib and object test_prog1.exp
chemfiles.lib(MMTF.obj) : error LNK2019: unresolved external symbol __imp_htonl referenced in function "class std::vector<char,class std::allocator<char> > __cdecl mmtf::encodeDeltaRecursiveFloat(class std::vector<float,class std::allocator<float> > const &,int)" (?encodeDeltaRecursiveFloat@mmtf@@YA?AV?$vector@DV?$allocator@D@std@@@std@@AEBV?$vector@MV?$allocator@M@std@@@3@H@Z)
chemfiles.lib(MMTF.obj) : error LNK2019: unresolved external symbol __imp_htons referenced in function "class std::vector<char,class std::allocator<char> > __cdecl mmtf::encodeDeltaRecursiveFloat(class std::vector<float,class std::allocator<float> > const &,int)" (?encodeDeltaRecursiveFloat@mmtf@@YA?AV?$vector@DV?$allocator@D@std@@@std@@AEBV?$vector@MV?$allocator@M@std@@@3@H@Z)
chemfiles.lib(MMTF.obj) : error LNK2019: unresolved external symbol __imp_ntohl referenced in function "public: void __cdecl mmtf::BinaryDecoder::decode<class std::vector<signed char,class std::allocator<signed char> > >(class std::vector<signed char,class std::allocator<signed char> > &)const " (??$decode@V?$vector@CV?$allocator@C@std@@@std@@@BinaryDecoder@mmtf@@QEBAXAEAV?$vector@CV?$allocator@C@std@@@std@@@Z)
chemfiles.lib(MMTF.obj) : error LNK2019: unresolved external symbol __imp_ntohs referenced in function "private: void __cdecl mmtf::BinaryDecoder::decodeFromBytes_(class std::vector<short,class std::allocator<short> > &)const " (?decodeFromBytes_@BinaryDecoder@mmtf@@AEBAXAEAV?$vector@FV?$allocator@F@std@@@std@@@Z)
chemfiles.lib(utils.obj) : error LNK2019: unresolved external symbol __imp_GetUserNameA referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl chemfiles::user_name(void)" (?user_name@chemfiles@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)
test_prog1.exe : fatal error LNK1120: 5 unresolved externals
```

One thing to note is that the compilation does not work with default /MT option, because presumably the .lib library was linked dynamically to the visual c/c++ runtimes. Only compilation with /MD option works.

After some digging, I found that the unresolved symbols are found in WS2_32.lib and Advapi32.lib. Explicitly linking to these in the command line works:

```
G:\mypath> cl /MD test_prog1.cpp /link G:\chemfiles\lib\chemfiles.lib WS2_32.lib Advapi32.lib
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29913 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

test_prog1.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\ostream(375): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\ostream(368): note: while compiling class template member function 'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(unsigned __int64)'
test_prog1.cpp(21): note: see reference to function template instantiation 'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(unsigned __int64)' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\ostream(641): note: see reference to class template instantiation 'std::basic_ostream<char,std::char_traits<char>>' being compiled
Microsoft (R) Incremental Linker Version 14.28.29913.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:test_prog1.exe
G:\chemfiles\lib\chemfiles.lib
WS2_32.lib
Advapi32.lib
test_prog1.obj
   Creating library test_prog1.lib and object test_prog1.exp
```
I am quite new to C/C++ and not really sure why this is happening. Also weird is the fact that compiling the cpp program produces an exports file and a library, whereas only the executable is required.

Is there a way not to link WS2_32.lib and Advapi32.lib explicitly (which are dependencies of the `chemfiles.lib`, not the program written)?

I attempted to create a DLL of chemfiles by using `-DBUILD_SHARED_LIBS=ON`, but `test-prog1.cpp` did not run when linked dynamically to the dll. (There was no output, the executable ran and then exited.) The files are attached (with extension changed to txt).

Any help would be greatly appreciated.

[test_prog1.cpp.txt](https://github.com/chemfiles/chemfiles/files/7006431/test_prog1.cpp.txt)
[testfile.pdb.txt](https://github.com/chemfiles/chemfiles/files/7006437/testfile.pdb.txt)

**Comment by Luthaf** [comment] 2021-08-18 10:58
Thanks a lot for taking the time to open such a detailed issue! I'm not using Windows on a daily basis, but these error looks a lot like some I already seen.

We are already linking to w2_s2 on windows here: https://github.com/chemfiles/chemfiles/blob/5ab49526dd000b6413d5bc7fd83ba75b7876b882/CMakeLists.txt#L169

but this might be only propagated to users of the chemfiles library if they are also using cmake, which does not seems to be what you are doing here, right? Just to check this, could you also share the content of the `CMAKE_INSTALL_PREFIX/lib/chemfiles/cmake` directory?

One possible fix could be to change the line in CMakeLists.txt from `target_link_libraries(chemfiles ws2_32)` to `target_link_libraries(chemfiles PUBLIC ws2_32)`. Let me know if that helps!

----

I don't know how `.lib` files work on windows, but on linux/macOS if you are linking to a static library you have to manually link all dependents doing something like `gcc my_program.o libchemfiles.a libw2_s2.a`. Are `.lib` files expected to carry dependencies on Windows? 

----

The library should work fine when compiled as a DLL (we are testing it on every change on CI), however you'll want to make sure the DLL is accessible to the program by setting the right PATH. Did you try running `test_prog1.exe` with a copy of `chemfiles.dll` in the same directory?

**Comment by Luthaf** [comment] 2021-08-18 11:02
> One thing to note is that the compilation does not work with default /MT option, because presumably the .lib library was linked dynamically to the visual c/c++ runtimes. Only compilation with /MD option works.

I don't think we are touching the `/MD` or `/MT` options in chemfiles build system, you could try setting them manually with `-DCMAKE_CXX_COMPILER_FLAGS="/MT"` and see if that helps. 

In general  we support compiling code with MSVC but since none of the core developers are using it as a main compiler, we might not be doing things as expected. Any improvement suggestion on this front is very welcome!

**Comment by ShoubhikRaj** [comment] 2021-08-19 09:06
@Luthaf Thanks for the quick reply! I usually use Linux for production calculations and my Windows laptop for analysis, and I have sometimes run into such issues where code wouldn't compile on Windows, in the past.

>but this might be only propagated to users of the chemfiles library if they are also using cmake, which does not seems to be what you are doing here, right? Just to check this, could you also share the content of the CMAKE_INSTALL_PREFIX/lib/chemfiles/cmake directory?

No, you are right. I am not using cmake to compile my program, I am compiling it from command line with `cl`. The contents of the directory are attached as a zipped folder: [cmake-chemfiles.zip](https://github.com/chemfiles/chemfiles/files/7012998/cmake-chemfiles.zip).

I tried the fix that you mentioned (`target_link_libraries(chemfiles PUBLIC ws2_32`), however I am still getting the same unresolved externals errors, which have to be fixed by explicitly linking to the WS2_32.lib and Advapi32.lib.

>Are .lib files expected to carry dependencies on Windows?

As far as I understand, static library `.lib` files should also carry all dependencies inside them. Unfortunately the problem is that in Windows, all low level API calls can only be done via DLLs. WS2_32.lib and Advapi32.lib are library files that point to `WS2_32.dll` and `Advapi32.dll`, and there is no way to link to those libraries statically.

So I believe what is happening is that when the static `chemfiles.lib` library is generated by the microsoft library manager, it leaves dependencies for those `dlls` because there is no other way. But when I am linking my program to `chemfiles.lib`, the linker thinks that it is a static library and it tries to resolve all dependencies recursively, and it can't because `chemfiles.lib` is not a fully static library. So, the linker has to be supplied with the other libraries explicitly.

>The library should work fine when compiled as a DLL (we are testing it on every change on CI), however you'll want to make sure the DLL is accessible to the program by setting the right PATH. Did you try running test_prog1.exe with a copy of chemfiles.dll in the same directory?

Yes, I tried running the program with the dll in the same directory, but it did not run. There was no output, no error message, it just stopped (and set ERRORLEVEL to -1). I am not familiar with CI, how do I check the build process there?

>I don't think we are touching the /MD or /MT options in chemfiles build system, you could try setting them manually with -DCMAKE_CXX_COMPILER_FLAGS="/MT" and see if that helps.

After looking at `CMakeCache.txt`, I believe that CMake is automatically setting the flag /MD in Windows. There are several other libraries including Advapi32.lib which are also automatically linked to:
```
//CXX compiler
CMAKE_CXX_COMPILER:FILEPATH=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe

//Flags used by the CXX compiler during all build types.
CMAKE_CXX_FLAGS:STRING=/DWIN32 /D_WINDOWS /W3 /GR /EHsc

//Flags used by the CXX compiler during DEBUG builds.
CMAKE_CXX_FLAGS_DEBUG:STRING=/MDd /Zi /Ob0 /Od /RTC1

//Flags used by the CXX compiler during MINSIZEREL builds.
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=/MD /O1 /Ob1 /DNDEBUG

//Flags used by the CXX compiler during RELEASE builds.
CMAKE_CXX_FLAGS_RELEASE:STRING=/MD /O2 /Ob2 /DNDEBUG

//Flags used by the CXX compiler during RELWITHDEBINFO builds.
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=/MD /Zi /O2 /Ob1 /DNDEBUG

//Libraries linked by default with all C++ applications.
CMAKE_CXX_STANDARD_LIBRARIES:STRING=kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib
```

I think the best solution to this would be to avoid a static `.lib` and use a `.dll`. Because then the user program would depend only on `chemfiles.dll` which would then depend on all of the system dll files. This would remove the need to explicitly link to the system libraries for the end user. But the dll compilation does not work properly as I mentioned before. Is there any test or anything I could do to figure out where the problem is coming from?

**Comment by Luthaf** [comment] 2021-08-20 08:17
> After looking at CMakeCache.txt, I believe that CMake is automatically setting the flag /MD in Windows. 

Right, these settings (anything inside `CMAKE_CXX_FLAGS_<CONFIG>`) are CMake default values, which you can change at the command line or using cmake-gui.

> No, you are right. I am not using cmake to compile my program, I am compiling it from command line with cl. The contents of the directory are attached as a zipped folder: cmake-chemfiles.zip.

Ok, as expected the `chemfiles-target.cmake` file contains the dependency information:

```cmake
set_target_properties(chemfiles PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ws2_32"
)
```

This mean that if you can build your code using cmake, then static library depenencies are taken care of. If you need to use another build system, I'm afraid that mean you'll have to explicitly link to `ws2_32` yourself.

Overall, if you are using a static build, I don't think there is much more we can do. But the DLL build should work as well, so let's try to fix this!

>  I am not familiar with CI, how do I check the build process there?

The most recent build on CI/MSVC is here: https://github.com/chemfiles/chemfiles/runs/3132498052, and we are running all tests there. However, the tests are also built using cmake, which might be passing extra flags to the compiler. We are also explicitly setting the PATH to include chemfiles.dll.

> Is there any test or anything I could do to figure out where the problem is coming from?

You could try building your test program using CMake, but I'm not sure how much it would help. Ideally you should not need to do this though. 

Did you try changing your PATH to include `C:\chemfiles\bin` (I think that's where the DLL is)?

Can you also share the DLL (ideally the full `C:\chemfiles\` folder, including headers & .lib file) & exe you compiled on your system so that I can give them a look in a VM?

**Comment by ShoubhikRaj** [comment] 2021-08-23 09:12
@Luthaf Thank you, I checked the CI build, and it uses Visual Studio as the generator. I was using microsoft's `nmake` as the generator in CMake, but I don't think that would make much of a difference.

I started CMake with: 
```
cmake -S. -B./build -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=debug -DCMAKE_INSTALL_PREFIX="G:/Installer/ChemFiles/test1" -DBUILD_SHARED_LIBS=ON -DCHFL_SYSTEM_ZLIB=OFF -DCMAKE_VERBOSE_MAKEFILE:BOOL=TRUE
```
Then 
```
cd build
nmake install
```

The installed files are attached (all files from `test1` folder): [chemfiles_dll.zip](https://github.com/chemfiles/chemfiles/files/7030611/chemfiles_dll.zip) . I have also tried putting the path to the dll into `PATH` but it does not change anything. The C++ code just stops without any error message or output.

I will also try building using Visual Studio and see if that changes anything.

**Comment by Luthaf** [comment] 2021-08-23 14:42
So I was able to reproduce this issue using the `chemfiles.dll` you shared. 

If I copy `chemfiles.dll` in the same folder as the output exe, and modify the program to add a print before opening the file, I get the program to output `"hello"` and then crash/exit without any other error message.

```cpp
#include <chemfiles.hpp>
#include <iostream>
#include <vector>

int main() {
    std::cout << "hello" << std::endl;

    chemfiles::Trajectory file("filename.xyz");
    chemfiles::Frame frame = file.read();

    std::vector<size_t> less_than_five;
    auto positions = frame.positions();

    for (size_t i=0; i<frame.size(); i++) {
        if (positions[i][0] < 5) {
            less_than_five.push_back(i);
        }
    }

    std::cout << "Atoms with x < 5: " << std::endl;
    for (auto i : less_than_five) {
        std::cout << "  - " << i << std::endl;
    }

    return 0;
}
```

I tried debugging the program, but I'm not familiar enough with WinDBG. I'll try installing lldb and using it instead.

---

Very strangely, if I use the C API instead of the C++ API (see example below), everything works fine. So it seems that the DLL loads without problem, but passing C++ objects back & forth to the DLL fails. I have no idea why this could be the case, maybe some ABI incompatibility? I see you used the debug build mode above, does the issue persist if you build the code in release mode? 

```
#include <chemfiles.h>
#include <stdio.h>
#include <stdlib.h>

int main(void) {
    CHFL_TRAJECTORY* file = chfl_trajectory_open("testfile.pdb", 'r');
    CHFL_FRAME* frame = chfl_frame();
    chfl_trajectory_read(file, frame);

    uint64_t natoms = 0;
    chfl_vector3d* positions = NULL;
    chfl_frame_positions(frame, &positions, &natoms);

    size_t* less_than_five = (size_t*)malloc((size_t)natoms * sizeof(size_t));

    size_t matched = 0;
    for (uint64_t i=0; i<natoms; i++) {
        if (positions[i][0] < 5) {
            less_than_five[matched] = (size_t)i;
            matched++;
        }
    }

    printf("Atoms with x < 5:\n");
    for (size_t i=0; i<matched; i++) {
        printf("  - %lu\n", less_than_five[i]);
    }

    free(less_than_five);
    chfl_free(frame);
    chfl_trajectory_close(file);

    return 0;
}
```

**Comment by ShoubhikRaj** [comment] 2021-08-24 10:15
@Luthaf Yes the problem persists even with release mode.

**Comment by Luthaf** [comment] 2021-09-09 14:47
So while I managed to re-create the issue using the `chemfiles.dll` file you shared, the problem goes away once I recompiled chemfiles ... 

Here are the step I took:

```
cd chemfiles
mkdir build
cd build
cmake -DBUILD_SHARED_LIB=ON -DCMAKE_INSTALL_PREFIX=C:\Chemfiles ..
cmake --build . --target install --config Release

cd ../../tests
# copy the code & testfile.pdb

cl .\test.cpp /I C:\Chemfiles\include\ /link C:\Chemfiles\lib\chemfiles.lib

./test.exe
# no missing DLL error, which is strange

cp C:\Chemfiles\bin\chemfiles.dll .
./test.exe
# works fine!
```

Can you try recompiling the code yourself, or linking against my version (
[Chemfiles.zip](https://github.com/chemfiles/chemfiles/files/7137515/Chemfiles.zip))?

**Comment by ShoubhikRaj** [comment] 2021-09-11 03:42
@Luthaf I tried recompiling the code, and you are right that the problem goes away.

What I can see is that when I use `nmake` as the generator for CMake, the dll gives error, but when I use the Visual Studio Generator (i.e. MSBuild), the dll works fine. Not sure why this is, but since Visual Studio works, I will use that. Maybe adding a line in the documentation that nmake does not work for dynamic link in Windows, would be beneficial but I leave that up to you.

Feel free to close the issue.

**Comment by Luthaf** [comment] 2021-09-13 09:44
I just rebuilt the DLL using "NMake Makefiles" as CMake generator, and then manually compiled a test program which worked fine. There might be something else at play here. 

I'll close this issue, and if someone else has similar problems please open a new issue!

**Closed by Luthaf** 2021-09-13 09:44 UTC
